"""empty message

Revision ID: 25760aba11db
Revises: 4c3fb44fbe2b
Create Date: 2026-01-06 02:21:08.576247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25760aba11db'
down_revision = '4c3fb44fbe2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
