"""empty message

Revision ID: 2db91a4f00ac
Revises: 25760aba11db
Create Date: 2026-01-07 20:57:54.382546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db91a4f00ac'
down_revision = '25760aba11db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=30), server_default='no name', nullable=False),
    sa.Column('last_name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('_password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
