"""initial

Revision ID: 3a4fa7842f69
Revises: 
Create Date: 2026-01-06 02:06:10.035950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4fa7842f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=30), server_default='no name', nullable=False),
    sa.Column('last_name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('email', sa.String(length=50), server_default='no mail', nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('_password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
