"""empty message

Revision ID: 6722e1775937
Revises: 3a4fa7842f69
Create Date: 2026-01-06 02:12:29.049235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6722e1775937'
down_revision = '3a4fa7842f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
