"""empty message

Revision ID: 920065a7aa80
Revises: 40c7e2f28994
Create Date: 2026-01-12 21:52:17.323393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920065a7aa80'
down_revision = '40c7e2f28994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=30), server_default='no name', nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=30), server_default=sa.text("'no name'"), nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
